pom.xml, src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
Adds the hibernate dependency and extends the Dialect class
=> Add Hibernate dep, extend dialect

pom.xml, src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTest.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java, src/test/java/com/google/cloud/spanner/hibernate/TestEntity.java, src/test/java/com/google/cloud/spanner/hibernate/util/TestEntity.java
related #3 
This sets up tests, dependencies, and classes for starting up Hibernate to actually generate the whole schema from a class.
=> Table Exporter setup tests and class

src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTest.java
fixes #11
overrides and tests the DDL dialect meta functions
=> DDL dialect functions

pom.xml, src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java, src/test/java/com/google/cloud/spanner/hibernate/util/SubTestEntity.java, src/test/java/com/google/cloud/spanner/hibernate/util/TestEntity.java
fixes #22
sets up tests and provides example tests for generating complete SQL and DML
=> Setup testing queries SQL and DML

src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
=> insert DML test

src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java
Check that a property annotated as the ID is present in all versions of Hibernate including ones where no-ID entities are allowed.
=> Enforce PK required check

src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTest.java
fixes #12 
unique constraints and cascade delete constraint
=> unique and cascade constraints

src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
=> functions and types mapping

src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
Add Table Name to PK error message to help with debugging.
=> Add Table Name to PK error message

src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java, src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java, src/test/java/com/google/cloud/spanner/hibernate/entities/TestEntity.java
related #17 
support element collections and helps w/ tests
=> Support tests that use element collection

src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java, src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java, src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java, src/test/java/com/google/cloud/spanner/hibernate/entities/Employee.java
added tests for generated ID table.
also changed mapping of numeric/decimal to string. However this requires JDBC support
=> added tests for generated value sequence table

.gitignore, google-cloud-spanner-hibernate-testing/src/main/java/org/hibernate/userguide/model/Payment.java, google-cloud-spanner-hibernate-testing/src/main/java/org/hibernate/userguide/model/Person.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/jpa/test/BaseEntityManagerFunctionalTestCase.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/sql/SQLTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/sql/SpaceShip.java, google-cloud-spanner-hibernate-testing/src/test/resources/hibernate.properties
Fix tests and initializes once
=> Fix tests and initializes once

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
fixes #6 
provides support for limit and offset (default is not supported).
=> Supports limit and offset in query

google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/hql/CallStatistics.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/hql/HQLTest.java
Initial commit of the HQL tests. Set with `@Ignore`; the following PR will make adjustments necessary for tests to pass.
=> initial commit of HQL tests

google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/BatchFetchingTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/DirectVsQueryFetchingTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/FetchModeJoinTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/FetchModeSelectTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/FetchModeSubselectTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/FetchingTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/GraphFetchingTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/GraphParsingTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/LazyCollectionTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/fetching/ProfileFetchingTest.java
related #52 
copying w/o modifications fetching tests
=> copying fetching tests WITHOUT modifications

google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/DiscriminatorNotNullSingleTableTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/DiscriminatorOptionsNotNullSingleTableTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/JoinTablePrimaryKeyJoinColumnTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/JoinTableTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/MappedSuperclassTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/SingleTableDiscriminatorFormulaTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/SingleTableTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/TablePerClassTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/polymorphism/DomainModelEntity.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/polymorphism/ExplicitPolymorphismTest.java
This adds the inheritance tests without any modifications.
=> Add Inheritance Tests without Modifications

google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/transactions/TransactionsTest.java
related #52
These tests actually required no modification.
=> Transactions tests moved over

google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/CheckTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/ColumnDefaultTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/IndexTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/SchemaGenerationTest.hbm.xml, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/SchemaGenerationTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/schema/UniqueConstraintTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/transactions/TransactionsTest.java
related #52 
These are copied unmodified except for custom table names and single commentary related to #75
=> Schema tests

google-cloud-spanner-hibernate-testing/src/main/java/org/hibernate/userguide/model/Phone.java
related #85
disable setting our driver doesn't handle properly.
=> Disable explicit timeout setting in two tests. 

google-cloud-spanner-hibernate-testing/pom.xml
This updates the JDBC jar to the latest version.
=> Updates JDBC jar to latest version

docs/pom.xml, docs/src/main/asciidoc/spanner.adoc, pom.xml
=> Initial Ref doc version

docs/src/main/asciidoc/spanner.adoc, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/jpa/test/BaseCoreFunctionalTestCase.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/inheritance/JoinTablePrimaryKeyJoinColumnTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/userguide/mapping/basic/SubselectTest.java
Also fixed ref doc. those other bulk id strategies produce incompatible syntax in queries.
=> test fixes

README.adoc
clarifying 3 features in docs.
=> Doc updates clarifying 3 features

pom.xml
See: https://issues.sonatype.org/browse/NEXUS-9138
=> Reorder modules to workaround NEXUS-9138

.kokoro/promote.sh, README.adoc, RELEASING.adoc, google-cloud-spanner-hibernate-dialect/pom.xml, google-cloud-spanner-hibernate-sample/pom.xml, google-cloud-spanner-hibernate-testing/pom.xml, pom.xml
* Added RELEASING.adoc to document the release process
* Moved the version up to 0.2.0.BUILD-SNAPSHOT
=> Post-release updates

google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml, google-cloud-spanner-hibernate-samples/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/README.adoc, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/com/example/CoffeeApplication.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/com/example/WebController.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/Coffee.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/CoffeeRepository.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/Customer.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/CustomerRepository.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/resources/application.properties, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/resources/templates/index.html, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/test/java/com/example/CoffeeApplicationTests.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/test/resources/application-test.properties
Adds a sample demonstrating usage of Hibernate Spanner through Spring Data JPA.
=> Add Spring Data JPA sample for Hibernate Spanner

google-cloud-spanner-hibernate-samples/basic-hibernate-sample/README.adoc, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/resources/hibernate.cfg.xml, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/test/resources/hibernate.properties
=> Fix basic sample so it runs outside of tests

README.adoc
Updates the Hibernate documentation for GA release.
Fixes #147.
=> Update the Hibernate Documentation

README.adoc
Polish the documentation for GA release.
- Reworded/reorganized some things
- Merge table from cloud docs to our doc.
=> Polish the documentation for GA release

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/test/java/com/example/PersonApplicationTest.java, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/test/resources/application.properties, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/test/resources/log4j.properties
This fixes the dialect to be able to run the Quarkus sample correctly and adds integration tests to verify the sample.
=> Fix the Quarkus sample and add Integration Tests

README.adoc, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/InterleavedTest.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/entities/Child.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/entities/GrandParent.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/entities/Parent.java
Updates the docs for the Interleaved annotation and also adds integration test to verify. feature.
Fixes #169.
Fixes #170.
=> Update docs for interleaved and implement integration tests.

README.adoc, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerDatabaseInfo.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerForeignKeyExporter.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaCreator.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaDropper.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaMigrator.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/MockJdbcUtils.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTests.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerForeignKeyExporterTests.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableStatementsTests.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/jpa/test/BaseEntityManagerFunctionalTestCase.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/jpa/test/EntityDependencyTracker.java, pom.xml
Updates the dialect to support foreign key generation during ddl generation.
Fixes #190.
=> Add support for generating Foreign Key statements during DDL generation

README.adoc, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/README.adoc, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/SampleApplication.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Album.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/CreditCardPayment.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Payment.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Person.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Singer.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/WireTransferPayment.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/resources/hibernate.cfg.xml, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/test/java/com/example/SampleApplicationTests.java
Provide an `@Interleaved` sample demonstrating how to setup the entities.
Fixes #196 .
=> Provide an Interleaved Tables Sample

README.adoc
Updates the JDBC driver version mentioned in docs. `1.17.0` is what contains numeric support.
=> Upgrade the JDBC Driver Version

README.adoc
Update docs with Mike's discovery about `persist` versus `save`.
Adds a TOC.
=> Update best practices doc

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
Fixes bug with limit/offset param binding being reversed.
Fixes #207.
=> Fix Limit/Offset parameter binding bug

README.adoc
Adds links to the codelab and samples in the README.
Fixes #167.
=> Add links to codelab and samples in README

google-cloud-spanner-hibernate-performance-testing/src/main/resources/log4j.properties
Missed a file in the last delete step in #216.
=> Delete extra logging config

pom.xml
Upgrades the log4j version.
Fixes #219.
=> Upgrade log4j version

README.adoc, pom.xml
Upgrade the JDBC driver version.
=> Upgrade JDBC driver version

README.adoc, pom.xml
Upgrades to the 2.0.0 JDBC driver version.
=> Upgrade to JDBC 2.0.0

README.adoc, google-cloud-spanner-hibernate-dialect/pom.xml, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml, google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/pom.xml, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml, google-cloud-spanner-hibernate-testing/pom.xml, pom.xml
Increments version numbers after release to `1.5.1-SNAPSHOT`.
=> Increment version numbers after release

pom.xml
Use the new sonatype endpoint to fix continuous build.
=> Fix sonatype endpoint

README.adoc, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerJsonType.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/internal/JsonJavaTypeDescriptor.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/internal/JsonSqlTypeDescriptor.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/JsonColumnTypeIT.java, google-cloud-spanner-hibernate-testing/src/test/java/org/hibernate/dialect/entities/JsonEntity.java
Defines a custom Hibernate user type to support JSON column types.
=> Add support for JSON column type

README.adoc, google-cloud-spanner-hibernate-dialect/pom.xml, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml, google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/pom.xml, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml, google-cloud-spanner-hibernate-testing/pom.xml, pom.xml
Increments version in preparation for `1.5.2-SNAPSHOT` development.
=> Bump versions after release

google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/README.adoc, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/test/java/com/example/PersonApplicationIT.java
#373 tracks fixing and re-enabling.
=> Disable Quarkus integration test

.github/release-please.yml, .github/release-trigger.yml, versions.txt
Introducing 3 new files in order to setup the pipeline for auto-release
1. release-please.yml
2. release-trigger.yml
3. versions.txt
=> chore: Set up release-please pipeline

.github/release-please.yml, .github/release-trigger.yml, versions.txt
deps: Bump hibernate.version to 5.6.9.Final
=> deps: Bump google-cloud-spanner-jdbc to 2.7.3

.github/release-please.yml, README.adoc
Include the README as a file that should be updated by release-please. This will ensure that the version numbers in the README file are also automatically updated.
=> build: automatically update README for new releases

google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Album.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/CreditCardPayment.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Payment.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Person.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/Singer.java, google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/entities/WireTransferPayment.java, google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/src/main/java/com/example/TransactionTypeDemo.java, google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/src/main/java/com/example/entities/Book.java, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/src/main/java/com/example/microprofile/Person.java, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/src/main/java/com/example/microprofile/PersonController.java, google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/src/main/java/com/example/microprofile/Producer.java, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/main/java/com/example/Person.java, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/main/java/com/example/PersonController.java, google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/main/java/com/example/PersonRepository.java, google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/src/main/java/codelab/Album.java, google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/src/main/java/codelab/Singer.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/Coffee.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/main/java/model/Customer.java
Updates the sample entities to use the jakarta package.
=> chore: sample entities to jakarta

google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/AbstractSchemaGenerationMockServerTest.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java
Also test other `hbm2ddl` configuration values.
=> test: test update schema

google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/AbstractSchemaGenerationMockServerTest.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java
Adds tests for dropping a schema.
=> test: drop schema

README.adoc
- Mutation limit has been raised to 40,000
- Only DML is supported, mutations are not.
=> docs: update limitation section on mutations

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/AbstractSpannerArrayType.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerBoolArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerBytesArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerDateArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerFloat64Array.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerInt64Array.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerJsonArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerNumericArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerStringArray.java, google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerTimestampArray.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/SampleModelIT.java, google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/model/AllTypes.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/SampleApplication.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/entities/Singer.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/service/RandomDataService.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/service/SingerService.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/test/java/com/google/cloud/spanner/sample/SampleApplicationMockServerTest.java
Adds standard UserType definitions for Spanner ARRAY data types.
Fixes #890
=> feat: add standard ARRAY types

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/pom.xml, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/entities/Singer.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/service/VenueService.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/test/java/com/google/cloud/spanner/sample/SampleApplicationEmulatorTest.java
- JSON columns would be generated as STRING(MAX).
- Adds a test that runs the JPA sample on the emulator during each build.
=> fix: JSON column DDL was generated as STRING

google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/entities/Singer.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/test/java/com/google/cloud/spanner/sample/SampleApplicationEmulatorTest.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/test/java/com/google/cloud/spanner/sample/SampleApplicationMockServerTest.java
=> docs: add sample for ColumnDefault

google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/service/BatchService.java, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/test/java/com/google/cloud/spanner/sample/SampleApplicationMockServerTest.java
Adds a sample for using max_commit_delay with Hibernate.
=> docs: max_commit_delay sample

google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/README.adoc, google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/service/ConcertService.java
Add an example for using isolation level repeatable read.
=> docs: add sample for isolation level repeatable read

README.adoc
Add a section for setting the isolation level to the README under the Performance Optimizations section.
=> docs: add isolation level performance hint to README

google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
=> chore: upgrade undertow-core
