src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTest.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
src/test/java/com/google/cloud/spanner/hibernate/util/TestEntity.java

fixes #3 
basic support for CREATE TABLE and DROP TABLE for simple use cases at alpha-level.
#17 will address the issue of creating and dropping tables when there are interleaved indexes or child-tables as needed for advanced features.

Table exporter basic CREATE TABLE DROP TABLE

---

.gitignore
testing/README.md
testing/databases.gradle
testing/documentation.gradle
testing/run-tests.py

This adds a script which allows you to run Hibernate integration tests against our Spanner Dialect locally.
This will clone (my fork) of the hibernate-orm repo, install the current version of Spanner Dialect to Maven local repo, and then run the hibernate tests.
Contributes to #4.

Write script to run integration testing the Hibernate Dialect

---

pom.xml
src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
src/test/java/com/google/cloud/spanner/hibernate/entities/Employee.java
src/test/java/com/google/cloud/spanner/hibernate/entities/SubTestEntity.java
src/test/java/com/google/cloud/spanner/hibernate/entities/TestEntity.java

This adds Exporters which return empty string[] for unsupported features of the dialect.
Fixes #9.

Add no-op exporters for the Dialect

---

src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java

Add support for the dialect to drop indices before dropping the Spanner table. Spanner requires indices to be dropped before you can drop the table itself.

Add Drop Indices before Dropping Table

---

pom.xml
src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTests.java
src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java

This fixes several tests and updates pom.xml so the tests get run.
Several tests were broken because they were not getting run during `mvn test`. This was due to the naming convention where tests are named `*Tests.java`; this requires an additional setting in pom.xml for the tests to get picked up by Maven and run.

Fixes the tests and update pom.xml test naming

---

google-cloud-spanner-hibernate-testing/pom.xml

Rename module artifact id to `google-cloud-spanner-hibernate-testing`.

Fix the test module's artifact name

---

pom.xml

Addresses security vulnerability in com.puppycrawl.tools:checkstyle versions which are < 8.18.

Upgrade puppycrawl to 8.18

---

.travis.yml

Configures the travis.yml to skip integration during a basic PR since the integration tests are starting to take a while to run.

Skip integration test during basic PR

---

README.adoc
pom.xml

This upgrades the project to Hibernate Core `5.4.6.Final` and Spanner JDBC Driver `1.7.0`.

Use latest versions of dependencies

---

google-cloud-spanner-hibernate-performance-testing/src/main/java/com/google/cloud/spanner/hibernate/ClientLibraryOperations.java
google-cloud-spanner-hibernate-performance-testing/src/main/java/com/google/cloud/spanner/hibernate/HibernateDriver.java
google-cloud-spanner-hibernate-performance-testing/src/main/java/com/google/cloud/spanner/hibernate/HibernateOperations.java
google-cloud-spanner-hibernate-performance-testing/src/main/java/com/google/cloud/spanner/hibernate/entities/Airport.java
google-cloud-spanner-hibernate-performance-testing/src/main/resources/hibernate.cfg.xml

This adds code to begin benchmarking some basic Hibernate operations.
More operations will be added, such as bulk DDL; this is not a complete list.

Add code to benchmark basic Hibernate operations

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaCreator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaDropper.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/StartBatchDdl.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
google-cloud-spanner-hibernate-performance-testing/src/main/java/com/google/cloud/spanner/hibernate/bulkddl/BulkDdlDriver.java

Implements batched DDL statements for schema creation and dropping.
This is achieved by providing implementations of `SpannerSchemaCreator` and `SpannerSchemaDropper` which are registered by the `SpannerSchemaManagementTool`. The `StartBatchDdl` and `RunBatchDdl` are auxiliary database objects which generate the batched DDL statements before and after table creation.
See test cases for examples. The DDL statements are now wrapped in between the start batch and run batch statements.
```
"START BATCH DDL",
"drop table `TestEntity_stringList`",
"drop table `test_table`",
"RUN BATCH"
```
Pending discussion with Hibernate folks on how to best integrate batched DDL statements for schema update operations.

Implement Batched DDL Statements

---

google-cloud-spanner-hibernate-testing/src/main/java/org/hibernate/userguide/model/Phone.java

Uncomments the `timeout` setting in the Hibernate tests using named queries.
Fixes #85.

Uncomment timeouts in named query tests

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/resources/hibernate.cfg.xml

This moves the setting of the Bulk ID strategy to the service contributor so users do not have to worry about setting it manually in configuration.

Move setting the Bulk ID strategy to the service contributor

---

pom.xml

Default is `false`. And that's what we want so that repository staging doesn't automatically release to Maven Central.

Remove undefined autoReleaseAfterClose property

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaCreator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaDropper.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaMigrator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/StartBatchDdl.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/TableDependencyTracker.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/MockJdbcUtils.java
pom.xml

Implement statement batching for Hibernate when running in Update mode.
Fixes #149.

Implement batching statements in Hibernate UPDATE mode

---

README.adoc
google-cloud-spanner-hibernate-performance-testing/pom.xml
pom.xml

The JDBC driver and Spanner Client Library versions must be in sync.
This removes the spanner dependency from the pom so that we simply rely on the spanner client lib version provided through the JDBC driver.

Fix the Spanner Client Lib dependency versions

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerDatabaseInfo.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaCreator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaDropper.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaMigrator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/MockJdbcUtils.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java

This checks the existence of tables and indices before attempting to create or delete them in Spanner. This is necessary since dropping an nonexistent table or creating a table with a duplicate name will both result in error.
Fixes #176.

Check existence of tables/indices before Schema create/delete

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java

This PR modifies the `INSERT` statement used for creating the hibernate_sequence table by deferring it until after the DDL batch is complete.
Fixes #171

Defer hibernate sequence DML to after DDL batch

---

README.adoc
google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-performance-testing/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

I completed the release steps for releasing version 1.1.0 and now am upgrading version numbers to 1.2.0.
Details:
- Version 1.1.0 artifact: https://search.maven.org/artifact/com.google.cloud/google-cloud-spanner-hibernate
- Github release: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/releases/tag/1.1.0
- Tag 1.1.0 is created for release.
- Codelab update (requires approval of suggestion):  https://codelabs.developers.google.com/codelabs/cloud-spanner-hibernate/
- Sample application update to 1.1.0: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/hibernate/pom.xml#L33

Update versions from 1.1.0 to 1.2.0

---

pom.xml

`addDefaultImplementationEntries` field of the jar plugin adds the following three fields:
```
Implementation-Title: Google Cloud Spanner Dialect for Hibernate ORM
Implementation-Version: 1.2.0-SNAPSHOT
Implementation-Vendor: Google LLC
```
Fixes #187

Add version fields to manifest

---

README.adoc
google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-performance-testing/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

I completed the release process for version 1.2.0 and am incrementing version numbers to 1.3.0.
- 1.2.0 released on Maven: https://search.maven.org/artifact/com.google.cloud/google-cloud-spanner-hibernate
- 1.2.0 Github Release created: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/releases
- Hibernate sample version has been updated to 1.2: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/spanner/hibernate/pom.xml#L33
- codelab updated: https://codelabs.developers.google.com/codelabs/cloud-spanner-hibernate/#4

Bump snapshot versions from 1.2.0 to 1.3.0

---

README.adoc

Add some docs about setting up a separate Maven profile to connect to different databases.
Partially addresses #194 .
And tomorrow during on meeting we can revisit whether we need to update our dialect so it can support multi db's in the next version.

Add docs about profiles to support multi-database use

---

README.adoc
google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-performance-testing/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

I released a new version of the hibernate dialect to accomodate the `NUMERIC` support.
Notes:
* Version 1.3.0 appearing in maven central: https://repo.maven.apache.org/maven2/com/google/cloud/google-cloud-spanner-hibernate-dialect/
* Codelab updated + republished: https://docs.google.com/document/d/1bcAKgl1vv86jxtcNZb0FkgFt3S_WKh2CAS5ottGQREY/edit#
* Release created:  https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/releases/tag/1.3.0
* Hibernate Sample: The versions for the java-samples get automatically upgraded by a bot

Bump snapshot version from 1.3.0 to 1.4.0 after release

---

.gitignore
README.adoc
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerServiceContributorTest.java

The Spanner dialect would add services and configuration, even if the Spanner dialect was not used, but was present on the classpath. This makes it impossible to develop an application that can run on both Cloud Spanner and other databases,
as the Spanner services would be loaded and used for all databases.
It also made it impossible to use for example H2 for testing purposes, while using Cloud Spanner for production.
This PR also contains a change for the `SpannerServiceContributorTest`, as that test would not work on Java 11. This version should work on both Java 8 and Java 11.

fix: do not add services if Spanner dialect is not used

---

README.adoc
google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-performance-testing/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

Bump the version numbers for the 1.4.0 release.
* Maven Central: https://repo.maven.apache.org/maven2/com/google/cloud/google-cloud-spanner-hibernate-dialect/
* Codelab versions: https://codelabs.developers.google.com/codelabs/cloud-spanner-hibernate/#4
* Github Release: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/releases/tag/1.4.0

Bump versions for 1.4.0 release

---

.gitignore
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/main/java/com/example/SampleApplication.java
pom.xml

The sample application should close the session and session factory when the application finishes. Failing to do so, will keep at least one JDBC connection open, which again could cause sessions to be kept around on the backend until they are garbage collected one hour later.
This chanage also turns off the cleanup of daemon threads by the maven-exec plugin. Otherwise it reports a large number of false positives of threads that are supposedly not shutdown. They are however closed by a shutdown hook after the check has been executed (the check is executed by this method: https://github.com/mojohaus/exec-maven-plugin/blob/d0e13ba1ddd383bc461f0efe547c91166ad789bf/src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java#L300)

fix: close session and sessionFactory when finished

---

google-cloud-spanner-hibernate-samples/basic-hibernate-sample/src/test/java/com/example/SampleApplicationIT.java
google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/src/test/java/com/example/PersonApplicationIT.java
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/src/test/java/codelab/AppIT.java
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/src/test/java/com/example/CoffeeApplicationIT.java
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

1. Renames some of the sample integration tests from `*Test[s]` --> `*IT` (matches Maven failsafe default).
2. Per our team chat, disables unit tests in the `google-cloud-spanner-hibernate-testing` because there ~140 classes that end in `Test` or `Tests` or `TestCase` that would need to be renamed. 
3. Fixes some build warnings/errors (there's still a Mockito error because it's usually a *really* old version of Mockito (from Dec 31, 2014)
4. Adds some naming consistency to modules

Split up unit tests from integration tests

---

.travis.yml

Sonar is rejecting builds from JDK8

Use JDK 11 in CI build

---

.kokoro/build.sh
.kokoro/stage.sh
.travis.yml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
google-cloud-spanner-hibernate-testing/src/test/resources/hibernate.properties
pom.xml

This removes the `disable-integration-test` profile, which should no longer be used after migrating to the fail-safe plugin which separates unit tests from integration tests. This profile was used to disable integration tests from being run by the surefire plugin back before I knew about differences between surefire vs. failsafe.

Delete the `disable-integration-test` profile

---

.github/dependabot.yml

Fixes https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/issues/294

ci: dependabot to ignore Quarkus 2

---

.github/dependabot.yml

Quarkus 2.x version update PRs are still being created by dependabot. Follow up to #294.

Make dependabot ignore Quarkus 2

---

google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerForeignKeyExporterTests.java
pom.xml

https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/328  failed. As per the release note (https://github.com/mockito/mockito/releases), Mockito 4.0 dropped Matchers in favor of ArgumentMatchers.

Adjusting Mockito 4.0 with ArgumentMatchers

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerUniqueDelegate.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerForeignKeyExporter.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerForeignKeyExporterTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
pom.xml

Running `./mvnw verify -f google-cloud-spanner-hibernate-testing/pom.xml -Dhibernate.show_sql=false -Dhibernate.connection.url='jdbc:cloudspanner:/projects/cloud-spanner-hibernate-ci/instances/test-instance/databases/test-database'`  locally results in a successful build.

Upgrade hibernate to 5.6.5.Final and fix compilation errors

---

.github/dependabot.yml

I could not find anything substantial in implementing the prefix-development part. I think for each of the package managers that is defined in "package-ecosystem" (like npm, maven etc), there exists a pre-defined development dependency group. And for the dependencies in this group, the prefix in the dependabot version-bump PR commit message will be what we define in "prefix-development" field. Also, the only fields in which we can specify "dependency-name" is either "allow" or "ignore". Now if this is true, there are good chances that the dependencies that we don't want to include exist in the pre-defined development dependency group. I could nowhere find what exists in the development dependency group for maven. Can you please give it a look? Maybe I don't know where to look.
For the …

Update dependabot.yml to add "prefix-development" (trying this out)

---

.github/dependabot.yml

**Doing this because we don't need to include these changes in the release notes.

chore: Update dependabot.yml to include prefix "chore(deps):" in samples

---

google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

We need a non snapshot release-version for the release bash script to run successfully. Will merge this in, and will trigger the stage job. A few things need to be done manually as this is the first time releasing via this process. Release-Please will take care of all this from the next time.
(This PR should fix the latest stage-job run [attempt](https://fusion2.corp.google.com/invocations/f52188aa-81ba-464f-970c-bced9b204b90/targets/cloud-java-frameworks%2Fgoogle-cloud-spanner-hibernate%2Fstage/log))

Bumping versions for releasing

---

.github/dependabot.yml

It looks to me that until dependabot/dependabot-core#4364 is implemented, we won't be able to specify a global configuration and a separate "samples" configuration to use a different commit prefix.
Instead, if we want samples to be treated differently (and we do, for semantic versioning), we'll have to enumerate each top level folder with a dedicated configuration. Mildly inconvenient for this repo, but will be a major annoyance for Spring Cloud GCP since it has lots of modules.

Specify individual directories in dependabot config

---

.kokoro/populate-secrets.sh
.kokoro/stage.sh

This will enable the release-tool-publish-reporter bot in release pr's created by release-please, so that we do not need to go to fusion separately to check if the release build went through fine or not.

chore: Include release-tool-publish-reporter in release-please PR

---

google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml
google-cloud-spanner-hibernate-samples/microprofile-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/pom.xml
google-cloud-spanner-hibernate-samples/quarkus-jpa-sample/pom.xml
google-cloud-spanner-hibernate-samples/spanner-hibernate-codelab/pom.xml
google-cloud-spanner-hibernate-samples/spring-data-jpa-sample/pom.xml
google-cloud-spanner-hibernate-testing/pom.xml
pom.xml

This PR is for adding annotations in various pom.xml's so that the release-please snapshot PR can bump the versions wherever required. 
For identifying which pom.xml's need this bump, I have referred to the last manual snapshot bump release [PR](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/389).

Adding annotations for snapshot version bumps in pom.xml's

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java

The Cloud Spanner Hibernate dialect will include the statements `START BATCH DDL` and `RUN BATCH` as auxiliary database objects. This ensures that the entire schema migration is executed as a single DDL batch, which both improves the execution speed of the statements, as well as makes the parsing of all statements atomic. However, Hibernate will ignore any SQLException that is thrown when creating an auxiliary database object. This means that if the `RUN BATCH` statement returns a SQLException, for example because one of the DDL statements is invalid, Hibernate will just silently ignore the error and proceed as if the schema migration worked.
This is fixed in this PR by returning an exception that is not an instance of `SQLException` specifically when one of the statements `START BATCH …

fix: do not ignore exception during schema migration

---

CHANGELOG.md
README.adoc

- Updates `README.adoc` to reflect latest 1.5.6 release
- Updates `CHANGELOG.md` with notes for unreleased 1.5.5 version

chore: bump versions in readme and update changelog after release

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/BitReversedSequenceStyleGenerator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/BitReversedSequenceStyleGeneratorTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/entities/Customer.java

Adds support for bit-reversed sequences. These are recommended above normal, monotonically increasing sequences for Cloud Spanner, as using a monotonically increasing value for a primary key can cause write hot spots.
This change also fixes the initialization of the backing tables for these sequences. Normally, the Cloud Spanner Hibernate dialect would not insert a value into the table that is backing a sequence, unless it was the default `hibernate_sequence` table. This would mean that generators that used custom table would be generated, but initialized, which would mean that they would not work out of the box.

feat: support bit-reversed sequences

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerExtractionContext.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedUpdateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/MockJdbcUtils.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/entities/Invoice.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/schema/SpannerExtractionContextTest.java

Use a separate JDBC connection to extract additional metadata from the database. This prevents `Executing queries is not allowed for DDL batches` errors from occurring.
Fixes #480

fix: use separate JDBC connection for extraction

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerDialectTests.java

Adds a new SpannerDialect class that extends the SpannerDialect in the Hibernate core repository. The basic function and type registration is handled by the core dialect, which means that this Hibernate 6.x dialect in this repository is a lot smaller than the 5.4 dialect class.

chore: add SpannerDialect class

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerSqlAstTranslator.java

Adds a translator for LIKE statements, as Cloud Spanner does not support ESCAPE clauses.

chore: add translator for LIKE statements

---

.github/header-checker-lint.yml

The License header check does not support LGPL as a possible license: https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint
The entire check is however superfluous, as we already have a check for this header: https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/master/checkstyle/java.header

build: disable license header check as LGPL cannot be configured

---

.github/workflows/integration-emulator.yml
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/BasicIntegrationTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/HibernateIntegrationTestEnv.java
pom.xml

Adds infrastructure for running integration tests for the Cloud Spanner Hibernate dialect, and sets up a GitHub Actions workflow for actually running these integration tests against the emulator.

build: run integration tests against the emulator

---

google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/AbstractSchemaGenerationMockServerTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java

Split the schema generation test class into a concrete class with tests and an abstract class with the standard schema queries that are generated by the JDBC driver. This makes it easier to set up more schema generation tests, and to re-use the base setup for these tests.

chore: split schema generation test class into concrete and abstract class

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerExtractionContext.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaManagementTool.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/schema/SpannerExtractionContextTest.java

Fixes a JDBC connection leak during schema creation. The schema creation process would obtain an isolated JDBC connection from the pool to extract metadata. This connection was not released back into the pool when the DdlTransactionIsolator was released.

fix: JDBC connection was leaked during schema creation

---

README.adoc

- Update the version numbers in the README file
- Clarify which versions can be used with Hibernate 5.4
BEGIN_COMMIT_OVERRIDE
deps: requires Hibernate 6.3
Version 3.0.x of this library requires __Hibernate 6.3__.
This version is not compatible with Hibernate 5.4. You should use version 2.x
of this library if you want to continue working with Hibernate 5.4.
Version 3.0.0 was not successfully pushed to Maven Central, which is why
these release notes repeats the message regarding the upgrade to Hibernate 6.3.
See https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html
for a guide for upgrading from Hibernate 5 to Hibernate 6.
END_COMMIT_OVERRIDE

fix: update version numbers in README

---

README.adoc

Mutation limits have been updated to 80,000. 
Update README to reflect this, and correct link

docs: Update README.adoc to reflect updated mutation limits

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerUniqueDelegate.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerDatabaseInfo.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerForeignKeyExporter.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaCreator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaDropper.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerSchemaMigrator.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedCreateTableStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/MockJdbcUtils.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerForeignKeyExporterTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableStatementsTests.java

Ensures that the Hibernate dialect is able to handle multiple schemas, potentially with tables with the same name in different schemas. This change does not introduce any specific support for named schemas, only preparations that ensure that nothing breaks if named schemas are used.

feat: prepare for named schemas

---

google-cloud-spanner-hibernate-dialect/pom.xml
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/SampleModelIT.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/model/Venue.java

Hibernate tried by default to insert columns that had been annotated with `@JdbcTypeCode(SqlTypes.JSON)` as a STRING instead of JSON. This change adds a default type registration for JSON that does include the correct type code with the value.

fix: Hibernate would insert JSON as STRING

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/SampleModelIT.java

Null values for JSON columns were inserted with type STRING, and then rejected by Cloud Spanner. This change also overrides the setNull methods, so these also explicitly state that the null value is a JSON.

fix: JSON nulls were inserted as STRINGs and rejected

---

pom.xml

Hibernate 6.x requires Java 11, and all underlying projects therefore also use Java 11. This updates the Java version in the parent project as well.

deps: bump Java version to 11 in parent project

---

google-cloud-spanner-hibernate-samples/pom.xml

These Spring samples use Spring Boot 3.x to be compatible with Hibernate 6, but Spring Boot 3.x is only compatible with JDK 17 or later. Spring Boot 2.x is not compatible with Hibernate 6.

ci: only test spring samples when using JDK 17 or later

---

google-cloud-spanner-hibernate-samples/pom.xml

Quarkus 3.7+ requires JDK 17 as a minimum. (https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7)
The sample in this repository currently uses 3.10.1.
See also recent Cloud Build failure: https://pantheon.corp.google.com/cloud-build/builds/0764fe35-8924-484a-b106-38b1a32b3f39?project=cloud-spanner-hibernate-ci

ci: run quarkus sample only with jdk17 or later

---

README.adoc
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/SpannerFloat32Array.java
google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/types/internal/ArrayJavaTypeDescriptor.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/GeneratedSelectStatementsTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SpannerTableExporterTests.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/entities/TestEntity.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/hints/HintsTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/SampleModelIT.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/it/model/AllTypes.java

Adds support for `FLOAT32` to the Spanner Hibernate dialect. Note that Hibernate by default maps `java.lang.float` fields to the JDBC type `FLOAT`, which is the equivalent of `DOUBLE`, meaning that these fields by default use `FLOAT64` on Spanner.
Add `@JdbcTypeCode(Types.REAL)` to your field declaration to ensure that a `FLOAT32` column is used.

feat: support float32 type

---

google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerSqlAstTranslator.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/HibernateMockSpannerServerTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/SchemaGenerationMockServerTest.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/entities/Album.java
google-cloud-spanner-hibernate-dialect/src/test/java/com/google/cloud/spanner/hibernate/entities/Singer.java
google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample/src/main/java/com/google/cloud/spanner/sample/entities/Singer.java

Hibernate by default uses the array_contains function when a predicate is created to search for entities where the ID is in an array of elements. array_contains is however not a supported function in Spanner GoogleSQL, and also using `in unnest(@values)` is more efficient on Spanner.
The `visitInArrayPredicate` method is therefore now overridden in the Spanner dialect and uses an `in unnest(@values)` construct instead.
Fixes #1546

fix: use unnest instead of array_contains

---

.github/workflows/integration-emulator.yml
.github/workflows/integration.yml

Attempt to fix the build errors in https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/1703

build: explicitly install tools locally before running tests
